### ISSUE TITLE
Unused jQuery?

### ISSUE THREAD

**Issue by Krinkle** [jrejaud/WWDCVideoWatcher#1]
It seems this plugin ships and loads jQuery, but doesn't use it? Perhaps it could be removed?

**Comment by jrejaud** [comment]
I think it does use jQuery though, granted I'm not an expert on the subject. Could you create a fork and try it without jQuery and report if it still works?

**Comment by Krinkle** [comment]
Aside from the jQuery library file, there is only 1 other JavaScript file in this repository: `content_script.js`.

It only interacts with two interfaces:
* `document`
* `console`

Both of these APIs, among many other, are defined by the web browser. jQuery defines 1 interface: `jQuery` (alias: `$`) - which is not used in this repository.

Below follows a brief introduction you might find useful:

> When running JavaScript code in a web browser you can typically interact with three layers:
> 
> 1. The JavaScript programming language. (Sometimes called "ECMAScript", the formal name of its specification.)
> 
> The language is what defines the structure of the code. E.g. the concept of creating variables, functions, loops, etc. As well as the types of values, like booleans, numbers, strings, arrays, objects. And much more.
> 
> This language is implemented in all web browsers. It is also available outside web browsers. For example, [Node.js](https://en.wikipedia.org/wiki/Node.js) is a run-time environment you can use from a server on the command-line, allowing you to create applications and web servers using JavaScript. (Similar to you might do with Java, or Python.)
> 
> <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide>
> <https://www.mediawiki.org/wiki/Learning_JavaScript>
> <https://github.com/getify/You-Dont-Know-JS#titles>
> 
> 2. Web APIs (DOM, HTML5 APIs, etc.)
> 
> Web browsers themselves are often written in C or C++. While this is mostly a closed box that runs separately from your JavaScript code, several interfaces have been defined by web browser vendors and standards bodies (like W3C, WHATWG, etc.) to give you a way to interact with this closed box through a sort of "bridge". These pre-defined interfaces are collectively known as the Web APIs, and are mounted as a foreign interfaces within the environment where your JavaScript code runs.
> 
> * <https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction>
> * <https://developer.mozilla.org/en-US/docs/Web/API/Document>
> * <https://developer.mozilla.org/en-US/docs/Web/API/Node>
> * <https://developer.mozilla.org/en-US/docs/Web/API/Element>
> * <https://developer.mozilla.org/en-US/docs/Web/API>
> 
> 3.. User code
> 
> Lastly, there is your own code. For example, after you declare `function doFoo(a, b) {}` and `var Example = { foo: doFoo }`, you can now call `Example.foo(1, 2)`.
> 
> Aside from defining your own functions and objects, you can also load code that others have written before. These are called libraries (or, frameworks). jQuery is an example of such a library. It provides classes and functions that, underneath, interact with `document` and other Web APIs. Similar to how one might do directly.
>
> -- @Krinkle

**Comment by bre7** [comment]
And even so, Apple already uses jQuery so there's no need to add another version.

Edit:
Updated version turned into a user script instead of extension:
* allows volume control with mouse wheel (only when used on the black area, to allow scrolling on the text below)
* play/pause with space bar
* disables auto play
* sets default volume to 20%
* double click to enter/exit fullscreen mode

https://gist.github.com/bre7/e615d385e72444e1e9e9a6ded2d875b2#file-wwdc-chrome-user-js

**Comment by jrejaud** [comment]
I meant I wasn't familiar with what jQuery was since it's often presented as equivalent to vanilla JS.

jQuery removed from the plug in and new version has been released on the chome store with these changes.
